[package]
name = "pack_images"
version = "0.1.0"
authors = ["Chevy Ray Johnston <happytrash@gmail.com>"]
edition = "2021"

[dependencies]
crunch = { path = "../.." }
image = { version = "0.24.5", default-features = false, features = ["png"] }
